#!/usr/bin/env python3
import os

path = r'C:\Users\douzh\Desktop\vrcsol\biome message.txt'
content = """[Windy]: A refreshing and cool wind passes through whe world...
[Snowy]: White snow and cold begin to cover the surroundings...
[Rainy]: Strong winds and showers sweep through the world...
[Sand Storm]: A harsh Sand Storm blocks your path...
[Hell]: A strong and violent energy of chaos overtakes the world...
[Starfall]: Beautiful and dreamy starlight pours into the world...
[Heaven]: A hand of angel leads you into divine place...
[Corruption]: Poisonous pollution spreads throughout the world...
[Null]: It's too dark here...
(start) [Dreamspace]: You begin to feel sleepy...
(end) [Dreamspace]: Waking up...
(start) [Glitch]: Unexpected error occurred.[Code 404]
(end) [Glitch]: [Code 404] has resolved.
(start) [Cyberspace]: Signal_Recieved | From: Island_SOL
(end) [Cyberspace]: Signal Lost.
"""

with open(path, 'w', encoding='utf-8') as f:
    f.write(content)

print(f"File restored: {path}")
print(f"File size: {os.path.getsize(path)} bytes")
print(f"Lines written: {len(content.splitlines())}")
